export {
  buildGoneproofDeletePayload,
  offsign,
  type BuildGoneproofDeletePayloadInput,
  type GoneproofDeletePayload,
  type OffsignInput,
} from './offsign.js';
export { checkDeclaredDeletionInDatabase } from './checkDeclaredDeletionInDatabase.js';
export {
  assertDatabaseVerifier,
  createDatabaseVerifier,
  createMongoVerifier,
  createMysqlVerifier,
  createPostgresVerifier,
  createTestDatabaseVerifier,
  createWiredDeletionVerifier,
  buildSqlAbsentCheckQuery,
  hasWiredDeletionProps,
  resolveDatabaseVerifier,
  runDatabaseAbsentCheck,
  verifyDeletionContextFromOffsignInput,
  OffsignInvalidDatabaseIdentifierError,
  type CreateWiredDeletionVerifierParams,
  type MongoFindable,
  type MysqlQueryable,
  type PostgresQueryable,
} from './databaseVerifier.js';

export {
  buildBackendDeletionAttestation,
  signBackendDeletionAttestation,
  validateBackendDeletionAttestation,
  canonicalJson,
  attestationSigningMessage,
  attestationCanonicalBytes,
  ATTESTATION_EXTENSION_KEYS,
  BACKEND_ATTESTATION_SIGN_DOMAIN,
  sha256,
  deriveTransitionMaterial,
  TRANSITION_DERIVATION_VERSION,
  OffsignDatabaseVerifierRequiredError,
  OffsignDeletionNotVerifiedError,
} from '@together-alone/zombiedelete-core';

export type {
  BackendDeletionAttestationV1,
  SignedBackendDeletionAttestationV1,
  DatabaseEngine,
  DatabaseVerifier,
  OffsignDatabaseVerification,
  SqlAbsentRecordData,
  WiredDeletionData,
  WiredDeletionDatabaseType,
  WiredDeletionProps,
  VerifyDeletion,
  VerifyDeletionResult,
  VerifyDeletionContext,
  DeletionDatabaseCheckResult,
  CheckDeclaredDeletionParams,
} from '@together-alone/zombiedelete-core';
