/**
 * @deprecated Use `@together-alone/zombiedelete-server` — API-only OffSign SDK.
 * This package re-exports the server API for backward compatibility.
 */
export {
  offsign,
  issueAttestedDeletionReceipt,
  attestDeletionProof,
  issueDeletionCertificate,
  guardRestoreAgainstMktd03,
  queryMktd03Receipt,
  queryMktd03Status,
  type OffsignInput,
  type IssueAttestedDeletionReceiptParams,
  type AttestDeletionProofParams,
  type IssueDeletionCertificateParams,
  type IssueDeletionCertificateResult,
  type GuardRestoreAgainstMktd03Params,
  type RestoreGuardClient,
  type DeletionAuditMetadata,
  type IssuanceProgress,
  type ReceiptLookup,
  type DeletionDatabaseCheckResult,
  type Receipt,
  type SignedBackendDeletionAttestationV1,
  type OffsignDatabaseVerification,
  type WiredDeletionDatabaseType,
  type WiredDeletionProps,
  type RestoreGuardResult,
  type RestoreGuardPolicy,
  OffsignDeletionNotVerifiedError,
} from '@together-alone/zombiedelete-server';

export {
  checkDeclaredDeletionInDatabase,
  createDatabaseVerifier,
  createMongoVerifier,
  createMysqlVerifier,
  createPostgresVerifier,
  createWiredDeletionVerifier,
  preflightCommercial,
  assertCommercialPreflight,
  type DatabaseVerifier,
  type AllowanceStatusView,
  type SecurityStatusView,
} from '@together-alone/zombiedelete-server/internal';

export {
  verifyAttestationChain,
  verifySignedBackendAttestation,
  transitionMaterialFromAttestation,
  auditExtensionsFromSignedAttestation,
  ATTESTATION_EXTENSION_KEYS,
  validateMktd03DeletionAuditInput,
  sha256,
  receiptSummary,
  hexPreview,
  asBytes,
  issuanceErrorLabel,
  auditErrorLabel,
  TOMBSTONE_DELETION_STATE,
  OffSignCommercialError,
  type BackendDeletionAttestationV1,
  type SecurityPreflightResult,
  type OffSignCommercialErrorCode,
} from '@together-alone/zombiedelete-core';
